### ISSUE TITLE
chaset

### ISSUE THREAD

**Issue by fengxingxiang** [wzx99/CLIPOCR#1]
请问配置文件中的chaset后续使用到了吗？还是直接使用bpe的SimpleTokenizer。谢谢！

**Comment by wzx99** [comment]
方法里面识别模型和clip模型使用的tokenizer不一样，识别模型里面使用的是配置文件中的charset，bpe的SimpleTokenizer是clip模型里使用的

**Comment by fengxingxiang** [comment]
谢谢！
