### ISSUE TITLE
多行识别

### ISSUE THREAD

**Issue by fengxingxiang** [wzx99/CLIPOCR#2]
请问输入图片可以变更为诸如224*224这样的吗？即如parseq一样支持多行识别

**Comment by wzx99** [comment]
因为识别模型用了vit，里面有位置编码，识别时的输入尺寸需要和训练时的尺寸一致

**Comment by fengxingxiang** [comment]
只要保持训练和推理的图片尺寸一致就可以，那就是说如parseq一样可以支持多行识别啦

**Comment by wzx99** [comment]
应该不能直接进行多行识别，训练集里面没有这种数据，一般可以加检测器或者使用端到端的模型[https://github.com/baudm/parseq/issues/113](url)  [https://github.com/baudm/parseq/issues/74](url)

**Comment by fengxingxiang** [comment]
可以自己生成相关数据集，parseq是可以多行识别的，我弄过。如果clip这边您没有魔改过的话，应该也是可以的

**Comment by wzx99** [comment]
这样说的话生成数据集然后训练应该可以，识别模型的主要框架和parseq是一样的
